# ================== General ==================
Id: Microsoft.SyncToy
Publisher: Microsoft Corporation
Name: SyncToy
Author: Microsoft
Description: Synchronize files and folders between locations. Typical uses include sharing files, such as photos, with other computers and creating backup copies of files and folders.
AppMoniker: synctoy
Tags: sync backup share

# ================== License ==================
Homepage: https://www.microsoft.com/en-us/download/details.aspx?id=15155
License: Copyright (C) Microsoft Corporation
LicenseUrl: https://www.microsoft.com/en-us/servicesagreement/

# ================= Installer =================
Version: 2.1
InstallerType: exe
Installers:
  - Arch: x64
    Url: https://download.microsoft.com/download/6/c/4/6c406239-a648-4e01-833e-2c452deed3b6/SyncToySetupPackage_v21_x64.exe
    Sha256: 54cc8e77eb8205aa4f18d0725f2440fc35e543dc546158695d9954d71a36542a
    Scope: machine
    Language: en-US
